services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: books
      POSTGRES_DB: book_manager
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
